# Generated by Django 3.0.2 on 2020-02-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion_model',
            name='author',
            field=models.CharField(default='bryan', max_length=240),
        ),
    ]
